import React, { useState } from 'react'

const WatermarkingInfo = () => {
  const [isExpanded, setIsExpanded] = useState(false)

  return (
    <div className="card">
      <div 
        className="flex justify-between items-center cursor-pointer"
        onClick={() => setIsExpanded(!isExpanded)}
      >
        <h2 className="text-xl font-semibold">About AI Text Watermarking</h2>
        <svg 
          className={`w-6 h-6 transition-transform ${isExpanded ? 'transform rotate-180' : ''}`} 
          fill="none" 
          viewBox="0 0 24 24" 
          stroke="currentColor"
        >
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </div>
      
      {isExpanded && (
        <div className="mt-4 space-y-6">
          <section>
            <h3 className="text-lg font-medium mb-2">What is AI Text Watermarking?</h3>
            <p className="text-gray-700 dark:text-gray-300">
              AI text watermarking is the process of embedding subtle, often invisible patterns into 
              text generated by AI systems. These patterns serve as a digital signature that can later 
              be detected to identify AI-generated content. Unlike visible watermarks in images, 
              text watermarks are designed to be imperceptible to human readers.
            </p>
          </section>
          
          <section>
            <h3 className="text-lg font-medium mb-2">Common Watermarking Techniques</h3>
            <div className="space-y-3">
              <div className="p-3 bg-gray-50 dark:bg-gray-800 rounded-md">
                <h4 className="font-medium text-blue-600 dark:text-blue-400">Hidden Unicode Characters</h4>
                <p className="text-sm text-gray-700 dark:text-gray-300 mt-1">
                  Invisible characters like zero-width spaces, joiners, and direction markers are inserted 
                  between visible characters. These are completely invisible to humans but can be detected 
                  by software.
                </p>
                <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                  <span className="font-medium">Severity:</span> High - Very difficult to detect without tools
                </p>
              </div>
              
              <div className="p-3 bg-gray-50 dark:bg-gray-800 rounded-md">
                <h4 className="font-medium text-blue-600 dark:text-blue-400">Spacing Pattern Manipulation</h4>
                <p className="text-sm text-gray-700 dark:text-gray-300 mt-1">
                  Subtle modifications to spacing between words or characters, such as using double spaces 
                  in specific patterns or following mathematical sequences like prime numbers.
                </p>
                <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                  <span className="font-medium">Severity:</span> Medium - May be noticeable with careful reading
                </p>
              </div>
              
              <div className="p-3 bg-gray-50 dark:bg-gray-800 rounded-md">
                <h4 className="font-medium text-blue-600 dark:text-blue-400">Mathematical Sequences</h4>
                <p className="text-sm text-gray-700 dark:text-gray-300 mt-1">
                  Spacing or character patterns that follow mathematical progressions like Fibonacci sequences, 
                  prime numbers, or arithmetic progressions. For example, triple spaces might be inserted after 
                  words at positions 2, 3, 5, 7, 11, etc. (prime numbers).
                </p>
                <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                  <span className="font-medium">Severity:</span> High - Sophisticated and difficult to detect
                </p>
              </div>
              
              <div className="p-3 bg-gray-50 dark:bg-gray-800 rounded-md">
                <h4 className="font-medium text-blue-600 dark:text-blue-400">Statistical Word Choice</h4>
                <p className="text-sm text-gray-700 dark:text-gray-300 mt-1">
                  Some AI systems subtly bias word choices toward specific synonyms based on a predetermined 
                  pattern, creating a statistical signature that can be detected with analysis.
                </p>
                <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                  <span className="font-medium">Severity:</span> Low - Nearly impossible to detect without statistical analysis
                </p>
              </div>
            </div>
          </section>
          
          <section>
            <h3 className="text-lg font-medium mb-2">Why Watermarking is Used</h3>
            <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300">
              <li>To identify AI-generated content for transparency purposes</li>
              <li>To help distinguish between human and AI-written text</li>
              <li>To track the source of AI-generated content</li>
              <li>To assist in detecting potential misuse of AI text generation</li>
              <li>To comply with emerging regulations around AI-generated content</li>
            </ul>
          </section>
          
          <section>
            <h3 className="text-lg font-medium mb-2">Effectiveness of Different Techniques</h3>
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                <thead className="bg-gray-50 dark:bg-gray-800">
                  <tr>
                    <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Technique</th>
                    <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Detectability</th>
                    <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Robustness</th>
                    <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Human Perception</th>
                  </tr>
                </thead>
                <tbody className="bg-white dark:bg-gray-900 divide-y divide-gray-200 dark:divide-gray-800">
                  <tr>
                    <td className="px-3 py-2 text-sm">Hidden Unicode</td>
                    <td className="px-3 py-2 text-sm">Very High</td>
                    <td className="px-3 py-2 text-sm">Medium</td>
                    <td className="px-3 py-2 text-sm">Invisible</td>
                  </tr>
                  <tr>
                    <td className="px-3 py-2 text-sm">Double Spacing</td>
                    <td className="px-3 py-2 text-sm">Medium</td>
                    <td className="px-3 py-2 text-sm">Low</td>
                    <td className="px-3 py-2 text-sm">Slightly Noticeable</td>
                  </tr>
                  <tr>
                    <td className="px-3 py-2 text-sm">Prime Number Patterns</td>
                    <td className="px-3 py-2 text-sm">High</td>
                    <td className="px-3 py-2 text-sm">High</td>
                    <td className="px-3 py-2 text-sm">Barely Noticeable</td>
                  </tr>
                  <tr>
                    <td className="px-3 py-2 text-sm">Statistical Word Choice</td>
                    <td className="px-3 py-2 text-sm">Low</td>
                    <td className="px-3 py-2 text-sm">Very High</td>
                    <td className="px-3 py-2 text-sm">Undetectable</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </section>
          
          <section>
            <h3 className="text-lg font-medium mb-2">Avoiding Detection (Educational Purposes Only)</h3>
            <div className="p-3 bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-md">
              <p className="text-sm text-yellow-800 dark:text-yellow-400">
                <span className="font-medium">Note:</span> This information is provided for educational purposes only.
              </p>
            </div>
            <ul className="mt-3 list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300">
              <li>Run text through a watermark detection and removal tool (like this one)</li>
              <li>Manually edit and rephrase the text to disrupt statistical patterns</li>
              <li>Use text editors that normalize spacing and remove hidden characters</li>
              <li>Convert text to plain ASCII format to remove Unicode watermarks</li>
              <li>Pass content through multiple transformations (e.g., translation and back)</li>
            </ul>
          </section>
          
          <div className="p-3 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-md">
            <p className="text-sm text-blue-800 dark:text-blue-400">
              <span className="font-medium">Important:</span> As watermarking techniques evolve, detection and removal methods will need to adapt. This tool is regularly updated to detect the latest watermarking methods.
            </p>
          </div>
        </div>
      )}
    </div>
  )
}

export default WatermarkingInfo
